accounts/urls.py
from django.urls import path
from . import views
from .views import logout_view
from .views import signup_view

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, UserLoginView, show_project


app_name = "projects"

urlpatterns = [
    path("<int:id>/", show_project, name="show_project"),
    path("", ProjectListView.as_view(), name="list_projects"),
    path("login/", UserLoginView.as_view(), name="login"),
]

tracker/urls.py
from django.urls import include, path
from django.views.generic import RedirectView
from projects.views import list_projects

urlpatterns = [
    path(
        "", RedirectView.as_view(url="/projects/"), name="home"
    ),  # Add the "home" URL pattern
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("projects/", list_projects, name="list_projects"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name


class Task(models.Model):
    description = models.TextField()
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.description

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name


class Task(models.Model):
    project = models.ForeignKey(
        Project, related_name="project_tasks", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, null=True, related_name="tasks", on_delete=models.CASCADE
    )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ["username", "password1", "password2"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from .forms import LoginForm


def logout_view(request):
    logout(request)
    return redirect("login")


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("list_projects")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("list_projects")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from .models import Project
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, render
from django.db.models import Count


def get_project_queryset(request):
    projects = Project.objects.filter(owner=request.user)
    projects = projects.annotate(total_tasks=Count("task"))
    return projects


def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    tasks = project.task_set.all()  # Get all tasks associated with the project
    return render(
        request,
        "projects/project_detail.html",
        {"project": project, "tasks": tasks},
    )


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/project_list.html"
    context_object_name = "projects"

    def get_queryset(self):
        projects = super().get_queryset()
        projects = projects.filter(owner=self.request.user)
        # Annotate each project with the total number of tasks
        projects = projects.annotate(total_tasks=Count("tasks"))
        return projects


def list_projects(request):
    projects = Project.objects.all()
    return render(
        request, "projects/project_list.html", {"projects": projects}
    )


class UserLoginView(LoginView):
    template_name = "projects/login.html"

tasks/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Login</h1>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Login</button>
        </form>
      </div>
    </main>
  </body>
</html>

projects/templates/projects/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}My Django App{% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <h1>Welcome to My Django App</h1>
    {% endblock %}
  </body>
</html>

projects/templates/projects/project_detail.html
{% extends "base.html" %} {% block content %}
<h2>{{ project.name }}</h2>
<p>{{ project.description }}</p>

<h3>Tasks:</h3>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <td>{{ task.title }}</td>
      <td>{{ task.status }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="2">No tasks found.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

projects/templates/projects/project_list.html
{% extends "base.html" %} {% block content %}
<h2>Projects</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Tasks</th>
    </tr>
  </thead>
  <tbody>
    {% for project in projects %}
    <tr>
      <td>
        <a href="{% url 'projects:show_project' project.id %}"
          >{{ project.name }}</a
        >
      </td>
      <td>{{ project.total_tasks }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="2">No projects found.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}